name: release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish_pypi:
    name: "Publish package on PyPI"
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'commaai/body-jim'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Build and publish
      run: |
        bash release.sh "$PYPI_PAT"
