name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install package
      run: pip install -e .[dev]
    - name: Unit Tests
      run: |
        cd tests/; python -m unittest discover
  static_analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Static analysis
      run: |
        pre-commit run --all
